handlers=java.util.logging.FileHandler

java.util.logging.FileHandler.level=WARNING
java.util.logging.FileHandler.pattern=logs/auth.log
java.util.logging.FileHandler.limit=20000
java.util.logging.FileHandler.formatter=java.util.logging.SimpleFormatter

online.newspaper.backend.level=WARNING
org.springframework.level=WARNING
org.springframework.web.level=WARNING
org.hibernate.level=OFF